---
version: 2.1

executors:
  # Whenever the Go version is updated here, .promu.yml and .promu-cgo.yml
  # should also be updated.
  golang:
    docker:
    - image: circleci/golang:1.17

jobs:
  build:
    executor: golang
    steps:
    - checkout
    - run: make build

  test:
    executor: golang
    steps:
    - checkout
    - run: make test

  lint:
    executor: golang
    steps:
    - checkout
    - run: make check-license
    - run: wget -O- -nv https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s v1.43.0
    - run: ./bin/golangci-lint run --timeout 10m0s


workflows:
  version: 2
  mixtool:
    jobs:
    - lint:
        filters:
          tags:
            only: /.*/
    - test:
        filters:
          tags:
            only: /.*/
    - build:
        filters:
          tags:
            only: /.*/
