---
version: 2.1

executors:
  golang:
    docker:
    - image: cimg/go:1.21

jobs:
  build:
    executor: golang
    steps:
    - checkout
    - run: make build

  test:
    executor: golang
    steps:
    - checkout
    - run: make test

  lint:
    executor: golang
    steps:
    - checkout
    - run: make check-license

workflows:
  version: 2
  mixtool:
    jobs:
    - lint:
        filters:
          tags:
            only: /.*/
    - test:
        filters:
          tags:
            only: /.*/
    - build:
        filters:
          tags:
            only: /.*/
